pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:vkarkhanis/app-ui-vending-machine.git
          - cd app-ui-vending-machine.git
          - git push --mirror git@github.com:vkarkhanis/app-ui-vending-machine.git